### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-leireriel#1]
Really cool job @leireriel  !!!

Here you have some tips to improve the exercise:

- [x] Remember to convert input value string to a number
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [x] Use `===` instead of `==` for comparisons
- [x] Add HTML elements for the game: title, label and input, button, space for feedback (`div`, `p`) and number of trials
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Inputs must have a type attribute set to a valid value (text, number, mail, button..)

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by leireriel** [comment]
done! :)

**Comment by oneeyedman** [comment]
Super good job, @leireriel !

If you are up to a challenge check out these exercises from previous Adalabers:

- http://beta.adalab.es/dorcas-s2-evaluacion-intermedia-mariavioleta1417/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-maria-badanina/
- http://beta.adalab.es/dorcar-s2-evaluacion-intermedia-annabranco/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-beatrizAdalab/

;)

Here you have a cool gif:
![well done](https://media.giphy.com/media/26FL2NwYBOq3Z6C6Q/giphy.gif)
